###############################################################################
# Settings file for birdie stress tests
###############################################################################

# base URL of installation
BASE_URL='http://localhost:6543'

DB_FILE='sqlite:///fakeusers.sqlite'

# pre-registered users to consider during the test - run the initialize_db script first
#MAX_USERS=50
#MAX_USERS=500
MAX_USERS=500
#MAX_USERS=50000
#MAX_USERS=500000

# pre-generated users up to 100 -- must be created by running register.py manually
BASE_USERNAME='user_'

# bio sketch for all generated users
ABOUT='I am a fake user generated by multi mechanize series of stress tests'

# True Twitter stats (Craig Smith, December 1, 2013)
#
# unique monthly visitors = 36 million (2013-09-24)
# total number of tweets sent = 300 billion (2013-10-03)
# monthly active twitter users 231.7 million (2013-10-17)
# daily active twitter users = 100 million (2013-10-03)
# average number of followers per twitter user = 208 (2012-10-11)
# average number of tweets sent per day = 500 million (2013-10-03)
# average number of tweets per twitter user = 307 (2013-01-11)
# total number of twitter registered users =~ 1 billion (2013-09-16)
# number of monthly active twitter users that actually tweet = 117 million (2013-11-11)
# estimated percentage of twitter accounts that tweet monthly = 13% (2013-11-11)

# 1 mn test: (43.200 mn per month)
# 5364 active users (view - follow - unfollow)
# 2708 users that actually tweet (post_chirp)
# 347.200 tweets (post_chirp + RT) - 128 tweet/min/user !!!
# 833 unique visitors (visit)
